[package]
name = "advent_of_code_2024_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
documents = "0.1.2"
easy-ext = "1.0.2"
itertools = "0.13.0"
memoize = "0.4.2"
rayon = "1.10.0"
regex = "1.11.1"
